// `synapse env pull [--out=<path>] [--for=<type>] [--project=<id>] [--json]`
//
// Reads project-default env vars + writes them as a .env-shaped file.
// Output defaults to stdout (so `synapse env pull >> .env.production`
// works). `--out=<path>` writes to disk with mode 0600.
//
// Values are quoted using the same `quoteEnvValue` helper that
// `.env.local` uses (handles backslashes, double quotes, newlines).

const fs = require("node:fs");
const colors = require("../colors");
const { extractFlags, resolveProject } = require("./_resource");
const { quoteEnvValue } = require("../env-file");

const VALID_FORS = new Set(["dev", "prod", "preview"]);

function formatDotenv(configs, { header = true } = {}) {
  const lines = [];
  if (header) {
    lines.push("# Synapse-managed project-default env vars");
    lines.push("# Generated by `synapse env pull` — do not edit by hand;");
    lines.push("# re-run the command after changes upstream.");
  }
  for (const c of configs) {
    lines.push(`${c.name}=${quoteEnvValue(c.value)}`);
  }
  return lines.join("\n") + (lines.length > 0 ? "\n" : "");
}

module.exports = {
  name: "env pull",
  summary: "Print or write project-default env vars in .env format.",
  usage:
    "synapse env pull [--out=<path>] [--for=<dev|prod|preview>] [--project=<id>] [--json]",
  description: `Reads the project's default env vars and emits them as KEY="value" lines. Default: writes to stdout. With --out=<path>: writes to that file with mode 0600 (overwrites if exists).

Flags:
  --out=<path>       Write to a file with mode 0600 instead of stdout.
  --for=<type>       Filter to vars whose deploymentTypes include <type>.
  --project=<id>     Override the linked project.
  --json             Emits { count, body } instead of raw .env text.

Examples:
  synapse env pull
  synapse env pull --out=.env.synapse
  synapse env pull --for=prod > .env.prod`,

  // Re-exports for tests.
  formatDotenv,

  async run(args, ctx) {
    const { flags, rest } = extractFlags(args, {
      string: ["out", "for", "project"],
      boolean: ["json"],
    });
    if (rest.length > 0) {
      throw new Error(`Unexpected positional: ${rest[0]}.`);
    }
    const filter = typeof flags.for === "string" ? flags.for.toLowerCase() : null;
    if (filter && !VALID_FORS.has(filter)) {
      throw new Error(
        `Invalid --for: ${filter}. Must be one of: ${[...VALID_FORS].join(", ")}.`,
      );
    }
    const outPath = typeof flags.out === "string" ? flags.out : null;

    const resolveArgs = flags.project ? [`--project=${flags.project}`] : [];
    const { projectId, source } = resolveProject(ctx, resolveArgs);

    const resp = await ctx.api.listProjectEnvVars(projectId);
    let configs = resp.configs || [];
    if (filter) {
      configs = configs.filter(
        (c) => Array.isArray(c.deploymentTypes) && c.deploymentTypes.includes(filter),
      );
    }
    configs.sort((a, b) => a.name.localeCompare(b.name));

    const body = formatDotenv(configs);

    if (outPath) {
      fs.writeFileSync(outPath, body, { mode: 0o600 });
      try {
        fs.chmodSync(outPath, 0o600);
      } catch {
        // best-effort on systems without POSIX modes
      }
    }

    ctx.out.result(
      {
        projectId,
        projectSource: source,
        filter,
        count: configs.length,
        outPath,
        body,
      },
      (data, { stdout }) => {
        if (outPath) {
          ctx.out.info(
            `Wrote ${data.count} env var${data.count === 1 ? "" : "s"} to ${outPath} (mode 0600).`,
          );
          return;
        }
        // Plain .env text to stdout — no headers, no colours. The
        // operator may be piping into another file.
        stdout.write(body);
        if (configs.length === 0) {
          // The body is empty; tell the operator on stderr so they
          // notice (stdout pipe wouldn't show anything).
          ctx.out.info(colors.dim(`(no vars matched${filter ? ` --for=${filter}` : ""})`));
        }
      },
    );
  },
};
